version: 2.1
orbs:
  datree: datree/version-alignment-rule@1.0.0

jobs:
  extract-versions:
    docker:
      - image: circleci/circleci-cli:0.1.2709
    steps:
      - run: echo "running version extraction script"
      # this is a mock demo - running a script to extract the package versions that were installed during the build

workflows:
  build_and_test:
    jobs:
      - extract-versions
      - datree/version-alignment-rule:
          requires: 
            - extract-versions
          context: datree-api-key
          payload: '{
            "expected": 
              [{"name":"webpack-node-externals","category":"npm","version":"1.6.8"}],
            "actual":
              [{"name":"webpack-node-externals","category":"npm","version":"1.6.2"}]
          }'
