version: 2.1
orbs:
  datree: datree/compare-versions@dev:0.0.2

workflows:
  build_and_test:
    jobs:
      - datree/compare-versions:
          API_KEY: $API_KEY
          payload: '{"codeComponents": {"expected": [{"name":"webpack-node-externals","category":"npm","version":"1.7.2"},{"name":"webpack-dev-server","category":"npm","version":"2.11.1"}],"actual": [{"name":"webpack-node-externals","category":"npm","version":"1.7.2"},{"name":"webpack-dev-server","category":"npm","version":"2.11.3"}]}}'