orbs:
  datree: datree/policy@1.0.8
description: A circle-ci job to enforce Datree's pull request title convention rule
jobs:
  branch_name_convension:
    docker:
      - image: 'circleci/node:10'
    steps:
      - datree/branch-name-convention:
          issue_tracker: jira
  pull_request_title_convension:
    docker:
      - image: 'circleci/node:10'
    steps:
      - datree/pull-request-title-convention

version: 2.1
workflows:
  main:
    jobs:
      - branch_name_convension
      - pull_request_title_convension:
          context: datree-api-key
