version: 2.1
orbs:
  datree: datree/compare-versions@dev:0.0.6

jobs:
  extract-versions:
    docker:
      - image: circleci/circleci-cli:0.1.2709
    working_directory: ~/
    steps:
      - run: curl https://s3.amazonaws.com/datreeio-static/versions.json > ~/versions.json
      - persist_to_workspace:
          root: ~/
          paths:
            - versions.json

workflows:
  build_and_test:
    jobs:
      - extract-versions
      - datree/compare-versions:
          requires: 
            - extract-versions
          context: datree-api-key
          file_path: ./versions.json