version: 2.1
orbs:
  datree: datree/compare-versions@dev:0.0.6

workflows:
  build_and_test:
    jobs:
      - run:
          name: Extract verrsion
          command: curl s3://datreeio-static/versions.json > versions.json
      - datree/compare-versions:
          context: datree-api-key
          file_path: ./versions.json